"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import ReactCrop, { type Crop, type PixelCrop } from "react-image-crop";
import "react-image-crop/dist/ReactCrop.css";

export interface ImageCropDialogLabels {
  /** Modal heading, e.g. "Crop image". */
  title: string;
  /** Helper text above the crop area. */
  description: string;
  /** Primary confirm button — applies the crop. */
  applyCrop: string;
  /** Secondary button — uses the original image without cropping. */
  useOriginal: string;
  /** Cancel button — drops the image entirely. */
  cancel: string;
  /** Shown while the cropped Blob is being generated by the canvas. */
  processing: string;
}

interface Props {
  /** The file the user picked / dropped / pasted. The dialog reads it
   *  as an object URL so we can display it without a network round-trip. */
  file: File | null;
  labels: ImageCropDialogLabels;
  /** Resolves with the file to upload (cropped or original), or null
   *  if the user cancelled. Caller awaits this once per `file`. */
  onResolve: (result: File | null) => void;
}

/**
 * Modal that lets an editor crop the image they're about to insert.
 *
 * Implementation notes:
 *  - Built on `react-image-crop` (~12KB, no deps). It draws the crop
 *    rectangle + handles itself; we own the modal chrome and the
 *    "render the cropped pixels to a canvas → Blob" step.
 *  - The crop starts at the full image (so confirming without dragging
 *    is a no-op equivalent to "use original"). The "Use original"
 *    button skips the canvas round-trip and returns the source file.
 *  - Esc cancels, backdrop click cancels. Apply button auto-focused so
 *    the keyboard-driven path is one Enter away.
 *  - Cropping a huge image is done on a `<canvas>` sized to the crop
 *    rectangle in source pixels (not display pixels), so we don't lose
 *    resolution when the editor only sized the preview to fit the
 *    modal.
 */
export function ImageCropDialog({ file, labels, onResolve }: Props) {
  const open = file !== null;
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [crop, setCrop] = useState<Crop>();
  const [completedCrop, setCompletedCrop] = useState<PixelCrop | null>(null);
  const [processing, setProcessing] = useState(false);
  const imgRef = useRef<HTMLImageElement | null>(null);
  const applyBtnRef = useRef<HTMLButtonElement | null>(null);

  // Allocate / revoke the object URL when the file changes. Critical:
  // revoke on unmount or file swap so we don't leak Blob URLs.
  useEffect(() => {
    if (!file) {
      setImageUrl(null);
      setCrop(undefined);
      setCompletedCrop(null);
      return;
    }
    const url = URL.createObjectURL(file);
    setImageUrl(url);
    return () => URL.revokeObjectURL(url);
  }, [file]);

  // Esc cancels. Apply button focus on open is handled when the image
  // load fires (so the user lands on the primary action).
  useEffect(() => {
    if (!open) return;
    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") onResolve(null);
    }
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, [open, onResolve]);

  // Initialize the crop rectangle to the full image once it loads so
  // hitting "Apply crop" without dragging is a sensible no-op rather
  // than producing a 0-sized result.
  const onImageLoad = useCallback((e: React.SyntheticEvent<HTMLImageElement>) => {
    const { naturalWidth, naturalHeight, width, height } = e.currentTarget;
    setCrop({
      unit: "px",
      x: 0,
      y: 0,
      width,
      height,
    });
    setCompletedCrop({
      unit: "px",
      x: 0,
      y: 0,
      width: naturalWidth,
      height: naturalHeight,
    });
    applyBtnRef.current?.focus();
  }, []);

  // Use the original file unchanged.
  const handleUseOriginal = useCallback(() => {
    if (file) onResolve(file);
  }, [file, onResolve]);

  // Render the crop rectangle (in source-pixel coordinates) to a canvas
  // and convert to a File using the original file's type so format /
  // extension stay consistent.
  const handleApplyCrop = useCallback(async () => {
    if (!file || !imgRef.current || !completedCrop) return;
    const img = imgRef.current;

    // displayed → natural conversion factor
    const scaleX = img.naturalWidth / img.width;
    const scaleY = img.naturalHeight / img.height;

    const sourceX = completedCrop.x * scaleX;
    const sourceY = completedCrop.y * scaleY;
    const sourceW = completedCrop.width * scaleX;
    const sourceH = completedCrop.height * scaleY;

    // If the crop covers the whole image at source resolution, skip the
    // canvas round-trip — same as "use original".
    if (
      sourceX <= 0.5 &&
      sourceY <= 0.5 &&
      Math.abs(sourceW - img.naturalWidth) <= 1 &&
      Math.abs(sourceH - img.naturalHeight) <= 1
    ) {
      onResolve(file);
      return;
    }

    setProcessing(true);
    try {
      const canvas = document.createElement("canvas");
      canvas.width = Math.round(sourceW);
      canvas.height = Math.round(sourceH);
      const ctx = canvas.getContext("2d");
      if (!ctx) {
        onResolve(file); // fall back to original — better than nothing
        return;
      }
      ctx.drawImage(
        img,
        sourceX,
        sourceY,
        sourceW,
        sourceH,
        0,
        0,
        canvas.width,
        canvas.height,
      );

      // Prefer the source file's mime so we don't surprise the user
      // with a JPEG when they uploaded a PNG. PNG keeps transparency;
      // JPEG/WebP get a quality knob. SVG can't round-trip a canvas —
      // fall back to the original file.
      const mime =
        file.type === "image/svg+xml"
          ? null
          : file.type === "image/jpeg" || file.type === "image/webp"
            ? file.type
            : "image/png";

      if (!mime) {
        onResolve(file);
        return;
      }

      const blob = await new Promise<Blob | null>((resolve) =>
        canvas.toBlob(resolve, mime, 0.92),
      );

      if (!blob) {
        onResolve(file);
        return;
      }

      // Preserve original filename so the audit log + server-side
      // dedupe stays meaningful. The extension already matches because
      // we preserved the mime above.
      const cropped = new File([blob], file.name, {
        type: mime,
        lastModified: file.lastModified,
      });
      onResolve(cropped);
    } finally {
      setProcessing(false);
    }
  }, [file, completedCrop, onResolve]);

  if (!open || !imageUrl) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-bg/70 backdrop-blur-sm"
      role="dialog"
      aria-modal="true"
      aria-labelledby="image-crop-dialog-title"
      onClick={() => onResolve(null)}
    >
      <div
        className="relative w-[min(48rem,92vw)] max-h-[90vh] overflow-hidden rounded-card border border-border bg-surface shadow-2xl flex flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="p-6 pb-3 border-b border-rule">
          <h2
            id="image-crop-dialog-title"
            className="font-display text-lg font-semibold text-fg"
          >
            {labels.title}
          </h2>
          <p className="mt-1 text-sm text-fg-muted">{labels.description}</p>
        </div>

        <div className="p-6 flex-1 overflow-auto bg-bg-alt/40 flex items-center justify-center">
          <ReactCrop
            crop={crop}
            onChange={(c) => setCrop(c)}
            onComplete={(c) => setCompletedCrop(c)}
            ruleOfThirds
          >
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              ref={imgRef}
              src={imageUrl}
              alt=""
              onLoad={onImageLoad}
              style={{ maxHeight: "60vh", maxWidth: "100%", display: "block" }}
            />
          </ReactCrop>
        </div>

        <div className="p-4 border-t border-rule flex items-center justify-end gap-2 bg-surface">
          <button
            type="button"
            onClick={() => onResolve(null)}
            disabled={processing}
            className="inline-flex h-9 items-center justify-center rounded-pill border border-border bg-surface px-4 text-sm font-medium text-fg hover:bg-bg-alt disabled:opacity-50"
          >
            {labels.cancel}
          </button>
          <button
            type="button"
            onClick={handleUseOriginal}
            disabled={processing}
            className="inline-flex h-9 items-center justify-center rounded-pill border border-border bg-surface-sunk px-4 text-sm font-medium text-fg hover:bg-bg-alt disabled:opacity-50"
          >
            {labels.useOriginal}
          </button>
          <button
            ref={applyBtnRef}
            type="button"
            onClick={handleApplyCrop}
            disabled={processing || !completedCrop}
            className="inline-flex h-9 items-center justify-center rounded-pill bg-fg px-4 text-sm font-medium text-bg hover:opacity-90 disabled:opacity-50"
          >
            {processing ? labels.processing : labels.applyCrop}
          </button>
        </div>
      </div>
    </div>
  );
}
